// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // 1. 指定你的 Prisma Schema 文件的存放路径
  // 告诉工具你的数据库结构定义在这个文件中。
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // 当你运行迁移时，系统会自动执行 `tsx prisma/seed.ts`
    // 自动填充/播种（Seed）数据的命令
    seed: 'tsx prisma/seed.ts',
  },
  // 3. 数据库连接配置
  datasource: {
     // 动态从环境变量中读取名为 DATABASE_URL 的连接字符串
    // 在 Vercel 中，这个环境变量会自动由 Vercel Postgres 提供
    url: process.env["DATABASE_URL"],
  },
});
