import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 使用上下文
import ThemeProvider from "@/components/ThemeProvider";
import Sidebar from "@/components/Sidebar";
import AuthHeader from "@/components/AuthHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col w-screen h-screen overflow-hidden">
          <AuthHeader />
          <div className="flex gap-2 flex-1 bg-gray-200">
            <Sidebar />
            <div className="flex-1 bg-white p-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
